version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - daisyui
  - eslintcache
  - vercel
  - vite
  - vitest
  - svelte
  - wails
  - wailsjs
  - pnpm
  - tsconfig
ignoreWords: []
import: []
