version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bitwarden
  - daisyui
  - eslintcache
  - hotp
  - keepass
  - lastpass
  - otpauth
  - pnpm
  - svelte
  - totp
  - tsconfig
  - typia
  - vercel
  - vite
  - vitest
  - wails
  - wailsjs
ignoreWords: []
import: []
