// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {context} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function OpenFileDialog(arg1:internal.OpenDialogOptions):Promise<string>;

export function OpenMultipleFilesDialog(arg1:internal.OpenDialogOptions):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFileDialog(arg1:internal.SaveDialogOptions):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
