// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileDialogWithOptions(arg1) {
  return window['go']['main']['App']['OpenFileDialogWithOptions'](arg1);
}

export function OpenMultipleFilesDialog(arg1) {
  return window['go']['main']['App']['OpenMultipleFilesDialog'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialogWithOptions(arg1) {
  return window['go']['main']['App']['SaveFileDialogWithOptions'](arg1);
}
