// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFileDialogWithOptions(arg1:main.OpenDialogOptions):Promise<string>;

export function OpenMultipleFilesDialog(arg1:main.OpenDialogOptions):Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFileDialogWithOptions(arg1:main.SaveDialogOptions):Promise<string>;
