// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['FileService']['DeleteFile'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['FileService']['FileExists'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['FileService']['GetFileInfo'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['FileService']['OpenFileDialog'](arg1);
}

export function OpenMultipleFilesDialog(arg1) {
  return window['go']['main']['FileService']['OpenMultipleFilesDialog'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['FileService']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['FileService']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['FileService']['SaveFileDialog'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['FileService']['Startup'](arg1);
}
