export const FILE_FORMAT = {
  MAGIC_BYTES: new Uint8Array([0x42, 0x33, 0x4D, 0x36]), // "B3M6"
  HEADER_SIZE: 8,
  CURRENT_VERSION: 2,
  MAGIC_OFFSET: 0,
  VERSION_OFFSET: 4,
  KEY_DATA_LENGTH_OFFSET: 5,
  RESERVED_OFFSET: 7,
} as const
